<?php

/**
 * Plugin Name: Our Metabox
 * Description: Our Metabox
 * Plugin URI: http://#
 * Author: Mehedi
 * Author URI: http://#
 * Version: 1.0.0
 * License: GPL2
 * Text Domain: our-metabox
 * Domain Path: /languages/
 */
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */
function omb_admin_assest()
{
	wp_enqueue_style( 'dp_css', '//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css',null,time() );
	wp_enqueue_script( 'dp_js', plugin_dir_url( __FILE__ )."main.js",array('jquery','jquery-ui-datepicker'), time() , true );
}
add_action( 'admin_enqueue_scripts', 'omb_admin_assest' );

function meta_box_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function meta_box_add_meta_box() {
	add_meta_box(
		'meta_box-meta-box',
		__( 'Meta Box', 'meta_box' ),
		'meta_box_html',
		'post',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'meta_box_add_meta_box' );

function meta_box_html( $post) {
	wp_nonce_field( '_meta_box_nonce', 'meta_box_nonce' );
	$post_id = get_post_meta($post->ID , 'omb_img_id', true );
	$post_url = get_post_meta( $post->ID, 'omb_img_url', true );
	 ?>
	<p>
		<label for="meta_box_img"><?php _e( 'Images', 'meta_box' ); ?></label>
		<button name="meta_box_img" id="meta_box_img">Uplode Image</button>
		<div id="float_c">
			<?php 
			if (!empty($post_url)) {
				?>
				<img src="<?php echo $post_url; ?>" name="omb_img_url" id="omb_img_url" >
				<?php
			}

			 ?>
		</div>
	</p>	


<?php
}

function meta_box_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['meta_box_nonce'] ) || ! wp_verify_nonce( $_POST['meta_box_nonce'], '_meta_box_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	
	if (!empty($post_id)) {
		if ( isset( $_POST['omb_img_id'] ) )
		update_post_meta( $post_id, 'omb_img_id', esc_attr( $_POST['omb_img_id'] ) );
	}
	if (!empty($post_url)) {
		if ( isset( $_POST['omb_img_url'] ) )
		update_post_meta( $post_url, 'omb_img_url', esc_attr( $_POST['omb_img_url'] ) );
	}
	
}
add_action( 'save_post', 'meta_box_save' );

?>
